server:
  port: 8886
spring:
  application:
    name: jdk17test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gale-bolg.cn:3306/gale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: write
    password: zijiale215
  data:
    redis:
      port: 6379
      host: localhost

